"""add role permission scope assignments

Revision ID: 1fe1abe6f605
Revises: e32023229f46
Create Date: 2026-09-24 17:12:52.734656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe1abe6f605'
down_revision: Union[str, Sequence[str], None] = 'e32023229f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permission_scope_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_permission_id', sa.Integer(), nullable=False),
    sa.Column('scope_entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_permission_id'], ['role_permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permission_scope_assignments_role_permission_id'), 'role_permission_scope_assignments', ['role_permission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_permission_scope_assignments_role_permission_id'), table_name='role_permission_scope_assignments')
    op.drop_table('role_permission_scope_assignments')
    # ### end Alembic commands ###
