"""add membership roles

Revision ID: 3d7cd41cad94
Revises: 03f926e52f38
Create Date: 2026-09-24 16:55:44.200831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7cd41cad94'
down_revision: Union[str, Sequence[str], None] = '03f926e52f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_roles',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['company_memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', 'role_id')
    )
    op.create_unique_constraint('uq_company_membership_user_company', 'company_memberships', ['user_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_company_membership_user_company', 'company_memberships', type_='unique')
    op.drop_table('membership_roles')
    # ### end Alembic commands ###
