"""add industry catalog

Revision ID: 4bfefe2e8013
Revises: e8ba560a945d
Create Date: 2026-10-07 12:36:17.110884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bfefe2e8013'
down_revision: Union[str, Sequence[str], None] = 'e8ba560a945d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_industries_code'), 'industries', ['code'], unique=True)
    op.create_table('company_industries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'industry_id', name='uq_company_industry')
    )
    op.create_index(op.f('ix_company_industries_company_id'), 'company_industries', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_industries_industry_id'), 'company_industries', ['industry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_industries_industry_id'), table_name='company_industries')
    op.drop_index(op.f('ix_company_industries_company_id'), table_name='company_industries')
    op.drop_table('company_industries')
    op.drop_index(op.f('ix_industries_code'), table_name='industries')
    op.drop_table('industries')
    # ### end Alembic commands ###
