"""add workforce configuration

Revision ID: 56cc7a6c5c39
Revises: fe20b4ae4710
Create Date: 2026-09-29 17:03:44.200630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cc7a6c5c39'
down_revision: Union[str, Sequence[str], None] = 'fe20b4ae4710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workforce_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('attendance_mode', sa.String(length=30), nullable=False),
    sa.Column('shifts_enabled', sa.Boolean(), nullable=False),
    sa.Column('overtime_enabled', sa.Boolean(), nullable=False),
    sa.Column('late_marking_enabled', sa.Boolean(), nullable=False),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workforce_configurations')
    # ### end Alembic commands ###
