"""add scope to role permissions

Revision ID: 5dfa32bcfbfd
Revises: 3d7cd41cad94
Create Date: 2026-09-24 17:04:58.328828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dfa32bcfbfd'
down_revision: Union[str, Sequence[str], None] = '3d7cd41cad94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('scope', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_permissions', 'scope')
    # ### end Alembic commands ###
