"""add company branding

Revision ID: cdfe907de098
Revises: 1fe1abe6f605
Create Date: 2026-09-24 17:46:18.274442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdfe907de098'
down_revision: Union[str, Sequence[str], None] = '1fe1abe6f605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('color', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('logo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'logo')
    op.drop_column('companies', 'color')
    # ### end Alembic commands ###
