"""add clients and posts organization settings

Revision ID: fe20b4ae4710
Revises: 7dc2fe908baa
Create Date: 2026-09-29 16:29:03.095628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe20b4ae4710'
down_revision: Union[str, Sequence[str], None] = '7dc2fe908baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "organization_configurations",
        sa.Column(
            "clients_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "organization_configurations",
        sa.Column(
            "posts_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_configurations', 'posts_enabled')
    op.drop_column('organization_configurations', 'clients_enabled')
    # ### end Alembic commands ###
