BUILT_IN_ROLES = [
    {
        "name": "Company Admin",
        "description": "Manages the company, employees, settings, and access.",
        "permissions": [
            ("COMPANY_VIEW", "COMPANY"),
            ("COMPANY_UPDATE", "COMPANY"),
            ("COMPANY_BRANDING_VIEW", "COMPANY"),
            ("COMPANY_BRANDING_UPDATE", "COMPANY"),
            ("ORGANIZATION_VIEW", "COMPANY"),
            ("ORGANIZATION_UPDATE", "COMPANY"),
            ("WORKFORCE_VIEW", "COMPANY"),
            ("WORKFORCE_UPDATE", "COMPANY"),
            ("ROLE_VIEW", "COMPANY"),
            ("ROLE_CREATE", "COMPANY"),
            ("ROLE_UPDATE", "COMPANY"),
            ("ROLE_DELETE", "COMPANY"),
            ("ROLE_ASSIGN", "COMPANY"),

            ("EMPLOYEE_VIEW", "COMPANY"),
            ("EMPLOYEE_CREATE", "COMPANY"),
            ("EMPLOYEE_UPDATE", "COMPANY"),
            ("EMPLOYEE_DELETE", "COMPANY"),

            ("ATTENDANCE_VIEW", "COMPANY"),
            ("ATTENDANCE_CREATE", "COMPANY"),
            ("ATTENDANCE_UPDATE", "COMPANY"),
            ("ATTENDANCE_APPROVE", "COMPANY"),

            ("LEAVE_VIEW", "COMPANY"),
            ("LEAVE_CREATE", "COMPANY"),
            ("LEAVE_UPDATE", "COMPANY"),
            ("LEAVE_APPROVE", "COMPANY"),

            ("TASK_VIEW", "COMPANY"),
            ("TASK_CREATE", "COMPANY"),
            ("TASK_UPDATE", "COMPANY"),
            ("TASK_DELETE", "COMPANY"),

            ("TICKET_VIEW", "COMPANY"),
            ("TICKET_CREATE", "COMPANY"),
            ("TICKET_UPDATE", "COMPANY"),
            ("TICKET_DELETE", "COMPANY"),

            ("ASSET_VIEW", "COMPANY"),
            ("ASSET_CREATE", "COMPANY"),
            ("ASSET_UPDATE", "COMPANY"),
            ("ASSET_DELETE", "COMPANY"),
            ("ASSET_ASSIGN", "COMPANY"),

            ("REPORT_VIEW", "COMPANY"),
            ("REPORT_EXPORT", "COMPANY"),

            ("PAYROLL_VIEW", "COMPANY"),
            ("PAYROLL_PROCESS", "COMPANY"),
            ("PAYSLIP_VIEW", "COMPANY"),
        ],
    },
    {
        "name": "HR Manager",
        "description": "Manages employees, leave, attendance, and HR operations.",
        "permissions": [
            ("EMPLOYEE_VIEW", "COMPANY"),
            ("EMPLOYEE_CREATE", "COMPANY"),
            ("EMPLOYEE_UPDATE", "COMPANY"),

            ("ATTENDANCE_VIEW", "COMPANY"),
            ("ATTENDANCE_UPDATE", "COMPANY"),
            ("ATTENDANCE_APPROVE", "COMPANY"),

            ("LEAVE_VIEW", "COMPANY"),
            ("LEAVE_CREATE", "COMPANY"),
            ("LEAVE_UPDATE", "COMPANY"),
            ("LEAVE_APPROVE", "COMPANY"),

            ("REPORT_VIEW", "COMPANY"),
            ("REPORT_EXPORT", "COMPANY"),
        ],
    },
    {
        "name": "Attendance Manager",
        "description": "Manages attendance and attendance approvals.",
        "permissions": [
            ("EMPLOYEE_VIEW", "COMPANY"),
            ("ATTENDANCE_VIEW", "COMPANY"),
            ("ATTENDANCE_CREATE", "COMPANY"),
            ("ATTENDANCE_UPDATE", "COMPANY"),
            ("ATTENDANCE_APPROVE", "COMPANY"),
        ],
    },
    {
        "name": "Leave Manager",
        "description": "Manages employee leave and leave approvals.",
        "permissions": [
            ("EMPLOYEE_VIEW", "COMPANY"),
            ("LEAVE_VIEW", "COMPANY"),
            ("LEAVE_CREATE", "COMPANY"),
            ("LEAVE_UPDATE", "COMPANY"),
            ("LEAVE_APPROVE", "COMPANY"),
        ],
    },
    {
        "name": "Payroll Manager",
        "description": "Manages payroll processing and payslips.",
        "permissions": [
            ("EMPLOYEE_VIEW", "COMPANY"),
            ("PAYROLL_VIEW", "COMPANY"),
            ("PAYROLL_PROCESS", "COMPANY"),
            ("PAYSLIP_VIEW", "COMPANY"),
            ("REPORT_VIEW", "COMPANY"),
            ("REPORT_EXPORT", "COMPANY"),
        ],
    },
    {
        "name": "Task Manager",
        "description": "Manages company tasks and task assignments.",
        "permissions": [
            ("EMPLOYEE_VIEW", "COMPANY"),
            ("TASK_VIEW", "COMPANY"),
            ("TASK_CREATE", "COMPANY"),
            ("TASK_UPDATE", "COMPANY"),
            ("TASK_DELETE", "COMPANY"),
        ],
    },
    {
        "name": "Ticket Manager",
        "description": "Manages company tickets and ticket operations.",
        "permissions": [
            ("EMPLOYEE_VIEW", "COMPANY"),
            ("TICKET_VIEW", "COMPANY"),
            ("TICKET_CREATE", "COMPANY"),
            ("TICKET_UPDATE", "COMPANY"),
            ("TICKET_DELETE", "COMPANY"),
        ],
    },
    {
        "name": "Asset Manager",
        "description": "Manages company assets and asset assignments.",
        "permissions": [
            ("EMPLOYEE_VIEW", "COMPANY"),
            ("ASSET_VIEW", "COMPANY"),
            ("ASSET_CREATE", "COMPANY"),
            ("ASSET_UPDATE", "COMPANY"),
            ("ASSET_DELETE", "COMPANY"),
            ("ASSET_ASSIGN", "COMPANY"),
        ],
    },
    {
        "name": "Team Manager",
        "description": "Manages team-level employee operations.",
        "permissions": [
            ("EMPLOYEE_VIEW", "TEAM"),
            ("ATTENDANCE_VIEW", "TEAM"),
            ("LEAVE_VIEW", "TEAM"),
            ("TASK_VIEW", "TEAM"),
            ("TASK_CREATE", "TEAM"),
            ("TASK_UPDATE", "TEAM"),
        ],
    },
    {
        "name": "Employee",
        "description": "Standard employee access to personal HRMS features.",
        "permissions": [
            ("EMPLOYEE_VIEW", "SELF"),
            ("ATTENDANCE_VIEW", "SELF"),
            ("ATTENDANCE_CREATE", "SELF"),
            ("LEAVE_VIEW", "SELF"),
            ("LEAVE_CREATE", "SELF"),
            ("LEAVE_UPDATE", "SELF"),
            ("TASK_VIEW", "SELF"),
            ("TASK_UPDATE", "SELF"),
            ("TICKET_VIEW", "SELF"),
            ("TICKET_CREATE", "SELF"),
            ("TICKET_UPDATE", "SELF"),
            ("PAYSLIP_VIEW", "SELF"),
        ],
    },
]